%YAML:1.0
---
left_cam:
    model_type: PINHOLE
    camera_name: camera
    image_width: 1241
    image_height: 376
    distortion_parameters:
       k1: 0
       k2: 0
       p1: 0
       p2: 0
    projection_parameters:
       fx: 7.070912000000e+02
       fy: 7.070912000000e+02
       cx: 6.018873000000e+02
       cy: 1.831104000000e+02

right_cam:
    model_type: PINHOLE
    camera_name: camera
    image_width: 1241
    image_height: 376
    distortion_parameters:
       k1: 0
       k2: 0
       p1: 0
       p2: 0
    projection_parameters:
       fx: 7.070912000000e+02
       fy: 7.070912000000e+02
       cx: 6.018873000000e+02
       cy: 1.831104000000e+02

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1, 0, 0, 0,
          0, 1, 0, 0,
          0, 0, 1, 0,
          0, 0, 0, 1]
body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1, 0, 0, 0.537150653267924,
          0, 1, 0, 0,
          0, 0, 1, 0,
          0, 0, 0, 1]
